# netlify.toml - Configuration file for Netlify deployment

[build]
  publish = "." # Deploy the current directory
  functions = "netlify/functions" # Path to your Netlify functions

# Redirect API requests to the serverless functions
[[redirects]]
  from = "/api/openai-api/*"
  to = "/.netlify/functions/openai-api"
  status = 200

# Handle direct access to netlify functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Default redirect to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
